=== jcmc0009/DAM/Lenguaje de marcas/Tareas/tarea 2/LM/Prácticas Xml - Dtd - Xsd/Practica3.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="desayunos">
    <xs:complexType>
        <xs:sequence>
           <xs:element ref="desayuno" maxOccurs="unbounded"/>
                  
        </xs:sequence>
    </xs:complexType> 
  </xs:element>

    <xs:element name="desayuno">
      <xs:complexType>
          <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="precio">
                  <xs:complexType>
                     <xs:simpleContent>
                          <xs:extension base="xs:integer">
                                <xs:attribute name="moneda">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                             <xs:enumeration value="euro"/>
                                             <xs:enumeration value="dolar"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>    
                          </xs:extension>
                     </xs:simpleContent>
                  </xs:complexType>
                </xs:element>
              <xs:element name="descripcion" type="xs:string"/>
              <xs:element name="calorias">
                  <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="600"/>
                            <xs:maxInclusive value="1000"/>
                        </xs:restriction>
                  </xs:simpleType>
              </xs:element>
          </xs:sequence>
      </xs:complexType>


  </xs:element>







  



</xs:schema>

=== jcmc0009/DAM/Lenguaje de marcas/Clase 23 - 10/Prácticas Xml - Dtd - Xsd/Practica3.xml
<?xml version="1.0" encoding="UTF-8"?>

<desayunos xmlns:xsi="http://w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Practica3.xsd">


    <desayuno>
        <nombre>Gofres Belgas</nombre>
        <precio moneda="euro">5.95</precio>
        <descripcion>Dos de nuestros famosos Gofres belgas con abundante sirope</descripcion>
        <calorias>650</calorias>
    </desayuno>
    <desayuno>
        <nombre>Gofres Belgas con fresas</nombre>
        <precio moneda="euro">7.95</precio>
        <descripcion>Ligeros gofres belgas cubiertos de fresa y nata montada</descripcion>
        <calorias>900</calorias>
    </desayuno>
    <desayuno>
        <nombre>Gofres Belgas con frutas del bosque</nombre>
        <precio moneda="euro">8.95</precio>
        <descripcion>Ligeros gofres belgas cubiertos con frutos del bosque y nata montada</descripcion>
        <calorias>900</calorias>
    </desayuno>
    <desayuno>
        <nombre>Tostada Francesa</nombre>
        <precio moneda="euro">4.50</precio>
        <descripcion>Dos gruesas rebanadas de nuestro pan franc√©s casero</descripcion>
        <calorias>600</calorias>
    </desayuno>
    <desayuno>
        <nombre>Desayuno de la casa</nombre>
        <precio moneda="euro">6.95</precio>
        <descripcion>Dos huevos, bacon o salchicha, tostada y patatas fritas</descripcion>
        <caalorias>950</caalorias>
    </desayuno>
</desayunos>
