<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE mensaje [

<!ELEMENT mensaje (remitente,destinatario,asunto,texto)>
<!ELEMENT remitente (nombre, email)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT destinatario (nombre, email)>

<!ELEMENT asunto (#PCDATA)>

<!ELEMENT texto (parrafo)*>

<!ELEMENT parrafo (#PCDATA)>

]>

<mensaje>
    <remitente>
        <nombre>Alfredo Reino</nombre>
        <email>alf@ibium.com</email>
    </remitente>
    <destinatario>
        <nombre>Bill Clinton</nombre>
        <email>president@whitehouse.gov</email>
    </destinatario>
    <asunto>Hola Bill</asunto>
    <texto>
        <parrafo>¿Hola qué tal?...</parrafo>
        <parrafo>Hace mucho tiempo que no escribes. A ver si llamas y quedamos pronto. </parrafo>
        <parrafo>Un saludo.</parrafo>
    </texto>
</mensaje>